load_from:
  - grpc_server:
      host: dagster-code-${PROJECT}-tijuana
      port: 4000
      location_name: "tijuana"
  - grpc_server:
      host: dagster-code-${PROJECT}-pathogens
      port: 4000
      location_name: "pathogens"
  - grpc_server:
      host: dagster-code-${PROJECT}-epidemiology
      port: 4000
      location_name: "epidemiology"
  - grpc_server:
      host: dagster-code-${PROJECT}-sim
      port: 4000
      location_name: "sim"
#  - grpc_server:
#      host: dagster-code-${PROJECT}-restricted
#      port: 4000
#      location_name: "restricted"
