name: "EpiNow2 Seasonal Forecasting - {{ DATE }}"
description: "Weekly forecasting input for COVID-19, Influenza, and RSV using surveillance data updated {{ LONG_DATE }}"
content:
  "CurrentData/COVID.csv":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{ PUBLIC_BUCKET }}"
    key: "pathogens/sandiego/sandiego_epidemiology/output/sandiego_epidemiology/{{ RUNID }}/processed_by_disease/COVID.csv"
  "CurrentData/FLU.csv":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{ PUBLIC_BUCKET }}"
    key: "pathogens/sandiego/sandiego_epidemiology/output/sandiego_epidemiology/{{ RUNID }}/processed_by_disease/FLU.csv"
  "CurrentData/RSV.csv":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{ PUBLIC_BUCKET }}"
    key: "pathogens/sandiego/sandiego_epidemiology/output/sandiego_epidemiology/{{ RUNID }}/processed_by_disease/RSV.csv"
  "ReportDelays/report-delays-COVID.RDS":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{  sims.RESILIENTSIMS_BUCKET }}"
    key: "report_delays/report-delays-COVID.RDS"
  "ReportDelays/report-delays-Influenza.RDS":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{  sims.RESILIENTSIMS_BUCKET }}"
    key: "report_delays/report-delays-Influenza.RDS"
  "ReportDelays/report-delays-RSV.RDS":
    type: "cloud_storage"
    provider: "s3"
    bucket: "{{  sims.RESILIENTSIMS_BUCKET }}"
    key: "report_delays/report-delays-RSV.RDS"
